### ISSUE TITLE
improve 'instructions'

### ISSUE THREAD

**Issue by joeclark-phd** [asu-cis-capstone/heroes#17]

**Comment by joeclark-phd** [comment]
Hi guys, your README has instructions for editing files in a GoDaddy account but that's not what I was looking for in release 0.2.  Instead, you need instructions for somebody to take your code and get it running.  A simple example is this one from this TalkShop project: https://github.com/asu-cis-capstone/talkshop/blob/master/Instructions.txt

Be sure you improve the instructions by the next milestone.

**Comment by charlesbrown3014** [comment]
Thank you.  I am making the entry now. It will be finished in about another
5 or 10 minutes.
